# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: abd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='abd.proto',
  package='adb',
  syntax='proto3',
  serialized_options=_b('\n\022edu.sjsu.cs249.adbP\001'),
  serialized_pb=_b('\n\tabd.proto\x12\x03\x61\x64\x62\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0cNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x0cRead1Request\x12\x10\n\x08register\x18\x01 \x01(\t\"1\n\rRead1Response\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\t\"B\n\x0cRead2Request\x12\x10\n\x08register\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\r\n\x05value\x18\x03 \x01(\t\"\r\n\x0b\x41\x63kResponse\"C\n\x0cWriteRequest\x12\x10\n\x08register\x18\x01 \x01(\t\x12\x12\n\ntimestampe\x18\x02 \x01(\x04\x12\r\n\x05value\x18\x03 \x01(\t2\xcb\x01\n\nABDService\x12\x31\n\x04name\x12\x16.google.protobuf.Empty\x1a\x11.adb.NameResponse\x12.\n\x05read1\x12\x11.adb.Read1Request\x1a\x12.adb.Read1Response\x12,\n\x05read2\x12\x11.adb.Read2Request\x1a\x10.adb.AckResponse\x12,\n\x05write\x12\x11.adb.WriteRequest\x1a\x10.adb.AckResponseB\x16\n\x12\x65\x64u.sjsu.cs249.adbP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_NAMERESPONSE = _descriptor.Descriptor(
  name='NameResponse',
  full_name='adb.NameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='adb.NameResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=75,
)


_READ1REQUEST = _descriptor.Descriptor(
  name='Read1Request',
  full_name='adb.Read1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='register', full_name='adb.Read1Request.register', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=109,
)


_READ1RESPONSE = _descriptor.Descriptor(
  name='Read1Response',
  full_name='adb.Read1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='adb.Read1Response.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='adb.Read1Response.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=160,
)


_READ2REQUEST = _descriptor.Descriptor(
  name='Read2Request',
  full_name='adb.Read2Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='register', full_name='adb.Read2Request.register', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='adb.Read2Request.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='adb.Read2Request.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=228,
)


_ACKRESPONSE = _descriptor.Descriptor(
  name='AckResponse',
  full_name='adb.AckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=243,
)


_WRITEREQUEST = _descriptor.Descriptor(
  name='WriteRequest',
  full_name='adb.WriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='register', full_name='adb.WriteRequest.register', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestampe', full_name='adb.WriteRequest.timestampe', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='adb.WriteRequest.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=312,
)

DESCRIPTOR.message_types_by_name['NameResponse'] = _NAMERESPONSE
DESCRIPTOR.message_types_by_name['Read1Request'] = _READ1REQUEST
DESCRIPTOR.message_types_by_name['Read1Response'] = _READ1RESPONSE
DESCRIPTOR.message_types_by_name['Read2Request'] = _READ2REQUEST
DESCRIPTOR.message_types_by_name['AckResponse'] = _ACKRESPONSE
DESCRIPTOR.message_types_by_name['WriteRequest'] = _WRITEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NameResponse = _reflection.GeneratedProtocolMessageType('NameResponse', (_message.Message,), {
  'DESCRIPTOR' : _NAMERESPONSE,
  '__module__' : 'abd_pb2'
  # @@protoc_insertion_point(class_scope:adb.NameResponse)
  })
_sym_db.RegisterMessage(NameResponse)

Read1Request = _reflection.GeneratedProtocolMessageType('Read1Request', (_message.Message,), {
  'DESCRIPTOR' : _READ1REQUEST,
  '__module__' : 'abd_pb2'
  # @@protoc_insertion_point(class_scope:adb.Read1Request)
  })
_sym_db.RegisterMessage(Read1Request)

Read1Response = _reflection.GeneratedProtocolMessageType('Read1Response', (_message.Message,), {
  'DESCRIPTOR' : _READ1RESPONSE,
  '__module__' : 'abd_pb2'
  # @@protoc_insertion_point(class_scope:adb.Read1Response)
  })
_sym_db.RegisterMessage(Read1Response)

Read2Request = _reflection.GeneratedProtocolMessageType('Read2Request', (_message.Message,), {
  'DESCRIPTOR' : _READ2REQUEST,
  '__module__' : 'abd_pb2'
  # @@protoc_insertion_point(class_scope:adb.Read2Request)
  })
_sym_db.RegisterMessage(Read2Request)

AckResponse = _reflection.GeneratedProtocolMessageType('AckResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACKRESPONSE,
  '__module__' : 'abd_pb2'
  # @@protoc_insertion_point(class_scope:adb.AckResponse)
  })
_sym_db.RegisterMessage(AckResponse)

WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEREQUEST,
  '__module__' : 'abd_pb2'
  # @@protoc_insertion_point(class_scope:adb.WriteRequest)
  })
_sym_db.RegisterMessage(WriteRequest)


DESCRIPTOR._options = None

_ABDSERVICE = _descriptor.ServiceDescriptor(
  name='ABDService',
  full_name='adb.ABDService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=315,
  serialized_end=518,
  methods=[
  _descriptor.MethodDescriptor(
    name='name',
    full_name='adb.ABDService.name',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_NAMERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='read1',
    full_name='adb.ABDService.read1',
    index=1,
    containing_service=None,
    input_type=_READ1REQUEST,
    output_type=_READ1RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='read2',
    full_name='adb.ABDService.read2',
    index=2,
    containing_service=None,
    input_type=_READ2REQUEST,
    output_type=_ACKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='write',
    full_name='adb.ABDService.write',
    index=3,
    containing_service=None,
    input_type=_WRITEREQUEST,
    output_type=_ACKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ABDSERVICE)

DESCRIPTOR.services_by_name['ABDService'] = _ABDSERVICE

# @@protoc_insertion_point(module_scope)
