# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import abd_pb2 as abd__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ABDServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.name = channel.unary_unary(
        '/adb.ABDService/name',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=abd__pb2.NameResponse.FromString,
        )
    self.read1 = channel.unary_unary(
        '/adb.ABDService/read1',
        request_serializer=abd__pb2.Read1Request.SerializeToString,
        response_deserializer=abd__pb2.Read1Response.FromString,
        )
    self.read2 = channel.unary_unary(
        '/adb.ABDService/read2',
        request_serializer=abd__pb2.Read2Request.SerializeToString,
        response_deserializer=abd__pb2.AckResponse.FromString,
        )
    self.write = channel.unary_unary(
        '/adb.ABDService/write',
        request_serializer=abd__pb2.WriteRequest.SerializeToString,
        response_deserializer=abd__pb2.AckResponse.FromString,
        )


class ABDServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def name(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def read1(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def read2(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def write(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ABDServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'name': grpc.unary_unary_rpc_method_handler(
          servicer.name,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=abd__pb2.NameResponse.SerializeToString,
      ),
      'read1': grpc.unary_unary_rpc_method_handler(
          servicer.read1,
          request_deserializer=abd__pb2.Read1Request.FromString,
          response_serializer=abd__pb2.Read1Response.SerializeToString,
      ),
      'read2': grpc.unary_unary_rpc_method_handler(
          servicer.read2,
          request_deserializer=abd__pb2.Read2Request.FromString,
          response_serializer=abd__pb2.AckResponse.SerializeToString,
      ),
      'write': grpc.unary_unary_rpc_method_handler(
          servicer.write,
          request_deserializer=abd__pb2.WriteRequest.FromString,
          response_serializer=abd__pb2.AckResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'adb.ABDService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
